# Generated by Django 5.1.6 on 2025-03-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0001_initial"),
        ("tasks", "0002_task_labels_alter_task_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="labels",
            field=models.ManyToManyField(to="labels.label", verbose_name="Метки"),
        ),
    ]
