# Generated by Django 5.1.6 on 2025-03-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0001_initial"),
        ("tasks", "0003_alter_task_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="labels",
            field=models.ManyToManyField(
                blank=True, to="labels.label", verbose_name="Метки"
            ),
        ),
    ]
