# Generated by Django 5.1.6 on 2025-03-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0002_status_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Имя"),
        ),
    ]
